// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameObject.proto

#include "GameObject.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_GameObject_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_GameObject_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_GameObjectConfigItem;
}  // namespace protobuf_GameObject_2eproto
namespace game {
class GameObjectConfigItemDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GameObjectConfigItem>
      _instance;
} _GameObjectConfigItem_default_instance_;
class GameConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GameConfig>
      _instance;
} _GameConfig_default_instance_;
}  // namespace game
namespace protobuf_GameObject_2eproto {
static void InitDefaultsGameObjectConfigItem() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_GameObjectConfigItem_default_instance_;
    new (ptr) ::game::GameObjectConfigItem();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::game::GameObjectConfigItem::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GameObjectConfigItem =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGameObjectConfigItem}, {}};

static void InitDefaultsGameConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_GameConfig_default_instance_;
    new (ptr) ::game::GameConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::game::GameConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_GameConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsGameConfig}, {
      &protobuf_GameObject_2eproto::scc_info_GameObjectConfigItem.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GameObjectConfigItem.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GameConfig.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::game::GameObjectConfigItem, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::game::GameObjectConfigItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::game::GameObjectConfigItem, filename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::game::GameObjectConfigItem, elementtype_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::game::GameConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::game::GameConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::game::GameConfig, configs_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::game::GameObjectConfigItem)},
  { 9, 15, sizeof(::game::GameConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::game::_GameObjectConfigItem_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::game::_GameConfig_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "GameObject.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020GameObject.proto\022\004game\"\177\n\024GameObjectCo"
      "nfigItem\022\020\n\010fileName\030\001 \002(\t\0224\n\013elementTyp"
      "e\030\002 \002(\0162\037.game.GameObjectConfigItem.Type"
      "\"\037\n\004Type\022\n\n\006OBJECT\020\000\022\013\n\007PICTURE\020\001\"9\n\nGam"
      "eConfig\022+\n\007configs\030\001 \003(\0132\032.game.GameObje"
      "ctConfigItem"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 212);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GameObject.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_GameObject_2eproto
namespace game {
const ::google::protobuf::EnumDescriptor* GameObjectConfigItem_Type_descriptor() {
  protobuf_GameObject_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GameObject_2eproto::file_level_enum_descriptors[0];
}
bool GameObjectConfigItem_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const GameObjectConfigItem_Type GameObjectConfigItem::OBJECT;
const GameObjectConfigItem_Type GameObjectConfigItem::PICTURE;
const GameObjectConfigItem_Type GameObjectConfigItem::Type_MIN;
const GameObjectConfigItem_Type GameObjectConfigItem::Type_MAX;
const int GameObjectConfigItem::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void GameObjectConfigItem::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GameObjectConfigItem::kFileNameFieldNumber;
const int GameObjectConfigItem::kElementTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GameObjectConfigItem::GameObjectConfigItem()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_GameObject_2eproto::scc_info_GameObjectConfigItem.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:game.GameObjectConfigItem)
}
GameObjectConfigItem::GameObjectConfigItem(const GameObjectConfigItem& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  filename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_filename()) {
    filename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filename_);
  }
  elementtype_ = from.elementtype_;
  // @@protoc_insertion_point(copy_constructor:game.GameObjectConfigItem)
}

void GameObjectConfigItem::SharedCtor() {
  filename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  elementtype_ = 0;
}

GameObjectConfigItem::~GameObjectConfigItem() {
  // @@protoc_insertion_point(destructor:game.GameObjectConfigItem)
  SharedDtor();
}

void GameObjectConfigItem::SharedDtor() {
  filename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GameObjectConfigItem::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GameObjectConfigItem::descriptor() {
  ::protobuf_GameObject_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GameObject_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GameObjectConfigItem& GameObjectConfigItem::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_GameObject_2eproto::scc_info_GameObjectConfigItem.base);
  return *internal_default_instance();
}


void GameObjectConfigItem::Clear() {
// @@protoc_insertion_point(message_clear_start:game.GameObjectConfigItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    filename_.ClearNonDefaultToEmptyNoArena();
  }
  elementtype_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool GameObjectConfigItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:game.GameObjectConfigItem)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string fileName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->filename().data(), static_cast<int>(this->filename().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "game.GameObjectConfigItem.fileName");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .game.GameObjectConfigItem.Type elementType = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::game::GameObjectConfigItem_Type_IsValid(value)) {
            set_elementtype(static_cast< ::game::GameObjectConfigItem_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                2, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:game.GameObjectConfigItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:game.GameObjectConfigItem)
  return false;
#undef DO_
}

void GameObjectConfigItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:game.GameObjectConfigItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string fileName = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->filename().data(), static_cast<int>(this->filename().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "game.GameObjectConfigItem.fileName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->filename(), output);
  }

  // required .game.GameObjectConfigItem.Type elementType = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->elementtype(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:game.GameObjectConfigItem)
}

::google::protobuf::uint8* GameObjectConfigItem::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:game.GameObjectConfigItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string fileName = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->filename().data(), static_cast<int>(this->filename().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "game.GameObjectConfigItem.fileName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->filename(), target);
  }

  // required .game.GameObjectConfigItem.Type elementType = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->elementtype(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.GameObjectConfigItem)
  return target;
}

size_t GameObjectConfigItem::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:game.GameObjectConfigItem)
  size_t total_size = 0;

  if (has_filename()) {
    // required string fileName = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->filename());
  }

  if (has_elementtype()) {
    // required .game.GameObjectConfigItem.Type elementType = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->elementtype());
  }

  return total_size;
}
size_t GameObjectConfigItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.GameObjectConfigItem)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string fileName = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->filename());

    // required .game.GameObjectConfigItem.Type elementType = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->elementtype());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameObjectConfigItem::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.GameObjectConfigItem)
  GOOGLE_DCHECK_NE(&from, this);
  const GameObjectConfigItem* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GameObjectConfigItem>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.GameObjectConfigItem)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.GameObjectConfigItem)
    MergeFrom(*source);
  }
}

void GameObjectConfigItem::MergeFrom(const GameObjectConfigItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.GameObjectConfigItem)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_filename();
      filename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filename_);
    }
    if (cached_has_bits & 0x00000002u) {
      elementtype_ = from.elementtype_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void GameObjectConfigItem::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.GameObjectConfigItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameObjectConfigItem::CopyFrom(const GameObjectConfigItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.GameObjectConfigItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameObjectConfigItem::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void GameObjectConfigItem::Swap(GameObjectConfigItem* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GameObjectConfigItem::InternalSwap(GameObjectConfigItem* other) {
  using std::swap;
  filename_.Swap(&other->filename_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(elementtype_, other->elementtype_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GameObjectConfigItem::GetMetadata() const {
  protobuf_GameObject_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GameObject_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GameConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GameConfig::kConfigsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GameConfig::GameConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_GameObject_2eproto::scc_info_GameConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:game.GameConfig)
}
GameConfig::GameConfig(const GameConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      configs_(from.configs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:game.GameConfig)
}

void GameConfig::SharedCtor() {
}

GameConfig::~GameConfig() {
  // @@protoc_insertion_point(destructor:game.GameConfig)
  SharedDtor();
}

void GameConfig::SharedDtor() {
}

void GameConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GameConfig::descriptor() {
  ::protobuf_GameObject_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GameObject_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GameConfig& GameConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_GameObject_2eproto::scc_info_GameConfig.base);
  return *internal_default_instance();
}


void GameConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:game.GameConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  configs_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool GameConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:game.GameConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .game.GameObjectConfigItem configs = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_configs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:game.GameConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:game.GameConfig)
  return false;
#undef DO_
}

void GameConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:game.GameConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .game.GameObjectConfigItem configs = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->configs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->configs(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:game.GameConfig)
}

::google::protobuf::uint8* GameConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:game.GameConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .game.GameObjectConfigItem configs = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->configs_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->configs(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.GameConfig)
  return target;
}

size_t GameConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.GameConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .game.GameObjectConfigItem configs = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->configs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->configs(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.GameConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const GameConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GameConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.GameConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.GameConfig)
    MergeFrom(*source);
  }
}

void GameConfig::MergeFrom(const GameConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.GameConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  configs_.MergeFrom(from.configs_);
}

void GameConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.GameConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameConfig::CopyFrom(const GameConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.GameConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameConfig::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->configs())) return false;
  return true;
}

void GameConfig::Swap(GameConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GameConfig::InternalSwap(GameConfig* other) {
  using std::swap;
  CastToBase(&configs_)->InternalSwap(CastToBase(&other->configs_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GameConfig::GetMetadata() const {
  protobuf_GameObject_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GameObject_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace game
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::game::GameObjectConfigItem* Arena::CreateMaybeMessage< ::game::GameObjectConfigItem >(Arena* arena) {
  return Arena::CreateInternal< ::game::GameObjectConfigItem >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::game::GameConfig* Arena::CreateMaybeMessage< ::game::GameConfig >(Arena* arena) {
  return Arena::CreateInternal< ::game::GameConfig >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
